In [2]:
# Imports
import folium
from folium.plugins import HeatMap
import pandas as pd
import geopandas as gpd

In [3]:

# Load the CSV files
url = 'https://gist.githubusercontent.com/mattkram/9684863843254402942dfede27af2cb7/raw/2590dd8185b833aacf247c0595edbb07a025a6d7/Smithsonian_VOTW_Holocene_Volcanoes.csv'
filepath = "C:/Users/maxje/OneDrive/Dokumenty/anaconda_projects/tectonicplates-master/GeoJSON/PB2002_boundaries.json"
volcanos = pd.read_csv(url)
tectonic_boundaries = gpd.read_file(filepath)
# Show the first 5 rows
tectonic_boundaries.head()

,LAYER,Name,Source,PlateA,PlateB,Type,geometry
0,plate boundary,AF-AN,Mueller et al. [1987],AF,AN,,"LINESTRING (-0.4379 -54.8518, -0.03883 -54.677..."
1,plate boundary,AF-AN,"by Peter Bird, October 2001",AF,AN,,"LINESTRING (7.77235 -54.396, 8.28834 -54.0326,..."
2,plate boundary,AN-AF,Lemaux et al. [2002],AN,AF,,"LINESTRING (32.1258 -46.9998, 31.8654 -47.2011..."
3,plate boundary,SO-AN,Lemaux et al. [2002],SO,AN,,"LINESTRING (32.1258 -46.9998, 33.1739 -47.2644..."
4,plate boundary,SO-AN,Mueller et al. [1987],SO,AN,,"LINESTRING (38.0827 -44.6188, 38.1937 -44.401,..."

In [4]:
# Transform geometry column to coordinates
tectonic_boundaries['coordinates'] = tectonic_boundaries.apply(lambda x: [(b,a) for (a,b) in list(x.geometry.coords)], axis='columns')
tectonic_boundaries.drop('geometry', axis=1, inplace=True)

In [5]:
# Show the first 5 rows
volcanos.Primary_Volcano_Type.value_counts()

Primary_Volcano_Type
Stratovolcano          541
Volcanic field         151
Submarine              114
Stratovolcano(es)      113
Shield                 100
Caldera                 71
Complex                 52
Pyroclastic cone(s)     36
Lava dome(s)            28
Shield(s)               17
Compound                13
Fissure vent(s)         12
Pyroclastic cone        11
Lava dome                8
Pyroclastic shield       8
Caldera(s)               8
Maar(s)                  7
Subglacial               5
Maar                     5
Crater rows              5
Tuff cone(s)             5
Fissure vent             4
Tuff cone                2
Submarine(es)            2
Lava cone                2
Stratovolcano?           2
Complex(es)              1
Cone(s)                  1
Tuff ring(s)             1
Lava cone(s)             1
Lava cone(es)            1
Explosion crater(s)      1
Name: count, dtype: int64

In [6]:
volcanos

,FID,Volcano_Number,Volcano_Name,Primary_Volcano_Type,Last_Eruption_Year,Country,Geological_Summary,Region,Subregion,Latitude,Longitude,Elevation,Tectonic_Setting,Geologic_Epoch,Evidence_Category,Primary_Photo_Link,Primary_Photo_Caption,Primary_Photo_Credit,Major_Rock_Type,GeoLocation
0,Smithsonian_VOTW_Holocene_Volcanoes.fid--d9082...,210010,West Eifel Volcanic Field,Volcanic field,-8300.0,Germany,The West Eifel Volcanic Field of western Germa...,Mediterranean and Western Asia,Western Europe,50.170,6.850,600,Rift zone / Continental crust (> 25 km),Holocene,Eruption Dated,https://volcano.si.edu/gallery/photos/GVP-0150...,The lake-filled Weinfelder maar is one of abou...,"Photo by Richard Waitt, 1990 (U.S. Geological ...",Foidite,POINT (50.17 6.85)
1,Smithsonian_VOTW_Holocene_Volcanoes.fid--d9082...,210020,Chaine des Puys,Lava dome(s),-4040.0,France,"The Chaîne des Puys, prominent in the history ...",Mediterranean and Western Asia,Western Europe,45.775,2.970,1464,Rift zone / Continental crust (> 25 km),Holocene,Eruption Dated,https://volcano.si.edu/gallery/photos/GVP-0880...,The central part of the Chaîne des Puys volcan...,Photo by Ichio Moriya (Kanazawa University).,Basalt / Picro-Basalt,POINT (45.775 2.97)
2,Smithsonian_VOTW_Holocene_Volcanoes.fid--d9082...,210030,Olot Volcanic Field,Volcanic field,NaN,Spain,The Olot volcanic field (also known as the Gar...,Mediterranean and Western Asia,Western Europe,42.170,2.530,893,Intraplate / Continental crust (> 25 km),Holocene,Evidence Credible,https://volcano.si.edu/gallery/photos/GVP-1199...,The forested Volcà Montolivet scoria cone rise...,Photo by Puigalder (Wikimedia Commons).,Trachybasalt / Tephrite Basanite,POINT (42.17 2.53)
3,Smithsonian_VOTW_Holocene_Volcanoes.fid--d9082...,210040,Calatrava Volcanic Field,Volcanic field,-3600.0,Spain,The Calatrava volcanic field lies in central S...,Mediterranean and Western Asia,Western Europe,38.870,-4.020,1117,Intraplate / Continental crust (> 25 km),Holocene,Eruption Dated,https://volcano.si.edu/gallery/photos/GVP-1185...,"Columba volcano, the youngest known vent of th...","Photo by Rafael Becerra Ramírez, 2006 (Univers...",Basalt / Picro-Basalt,POINT (38.87 -4.02)
4,Smithsonian_VOTW_Holocene_Volcanoes.fid--d9082...,211004,Colli Albani,Caldera,NaN,Italy,The Colli Albani (Alban Hills) complex immedia...,Mediterranean and Western Asia,Italy,41.730,12.700,949,Subduction zone / Continental crust (> 25 km),Holocene,Evidence Uncertain,https://volcano.si.edu/gallery/photos/GVP-0881...,The lake-filled Albano maar is part of the Alb...,Photo by Ichio Moriya (Kanazawa University).,Foidite,POINT (41.73 12.7)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1323,Smithsonian_VOTW_Holocene_Volcanoes.fid--d9082...,221294,Northern Lake Abaya Volcanic Field,Volcanic field,NaN,Ethiopia,The Northern Lake Abaya volcanic field consist...,Africa and Red Sea,Africa (northeastern) and Red Sea,6.760,37.970,1594,Intraplate / Continental crust (> 25 km),Holocene,Evidence Credible,https://volcano.si.edu/gallery/photos/GVP-1257...,Northern Lake Abaya Volcanic Field is largely ...,"Satellite image courtesy of Planet Labs Inc., ...",NaN,POINT (6.76 37.97)
1324,Smithsonian_VOTW_Holocene_Volcanoes.fid--d9082...,221330,Mega Volcanic Field,Volcanic field,NaN,Ethiopia,The Mega Volcanic Field in southern Ethiopia i...,Africa and Red Sea,Africa (northeastern) and Red Sea,3.971,38.213,1500,Rift zone / Intermediate crust (15-25 km),Holocene,Evidence Credible,https://volcano.si.edu/gallery/photos/GVP-1255...,"Cones, maars, lava flows, and craters of the M...","Satellite image courtesy of Planet Labs Inc., ...",NaN,POINT (3.971 38.213)
1325,Smithsonian_VOTW_Holocene_Volcanoes.fid--d9082...,312055,Stepovak Bay Group,Volcanic field,NaN,United States,The Stepovak Bay Group is a chain of four cone...,Alaska,Alaska Peninsula,55.917,-160.017,1633,Subduction zone / Continental crust (> 25 km),Holocene,Evidence Credible,https://volcano.si.edu/gallery/photos/GVP-1231...,Stepovak Bay 2 is part of the Stepovak Bay Gro...,Satellite image courtesy of Copernicus Sentine...,NaN,POINT (55.917 -160.017)
1326,Smithsonian_VOTW_Holocene_Volcanoes.fid--d9082...,244021,Malumalu,Submarine,NaN,United States,The Malumalu seamount (also called Southeast B...,New Zealand to Fiji,Samoan and Wallis Islands,-14.601,-169.787,-145,Intraplate / Oceanic crust (< 15 km),Holocene,Evidence Credible,NaN,NaN,NaN,NaN,POINT (-14.601 -169.787)
1327,Smithsonian_VOTW_Holocene_Volcanoes.fid--d9082...,371032,Fagradalsfjall,Fissure vent,2022.0,Iceland,Although the Fagradalsfjall fissure swarm has ...,Iceland and Arctic Ocean,Iceland (southwestern),63.895,-22.258,250,Rift zone / Oceanic crust (< 15 km),Holocene,Eruption Observed,NaN,NaN,NaN,NaN,POINT (63.895 -22.258)

In [20]:
# Create a folium map centered around a specific location
map_center = [0, 0]  # Center of the map (latitude, longitude)
volcano_map = folium.Map(location=map_center, zoom_start=2)

# Add markers for each volcano
for index, row in volcanos.iterrows():
    folium.Marker(
        location=[row['Latitude'], row['Longitude']],
        tooltip=row['Volcano_Name'],
        popup="<strong>Name: </strong>" + row['Volcano_Name'] + "<br><strong>Volcano type: </strong>" + row['Primary_Volcano_Type'],
        max_width="100%",
        icon=folium.Icon(color='red')
    ).add_to(volcano_map)

# Save the map to an HTML file
volcano_map.save('volcano_map.html')

# Display the map
volcano_map

In [31]:
# Create base map with tectonic plate boundaries
volcano_heatmap = folium.Map(location=map_center, zoom_start=2)

for i in range(len(tectonic_boundaries)):
    folium.PolyLine(locations=tectonic_boundaries.coordinates.iloc[i], weight=2, color='black').add_to(volcano_heatmap)



# Create heatmap of volcanos
HeatMap(data=volcanos[['Latitude','Longitude']], radius=20).add_to(volcano_heatmap)

# Display the map
volcano_heatmap

In [39]:
volcano_heatmap = folium.Map(location=map_center, zoom_start=2)
tectonic_plates = gpd.read_file(filepath)

# Add GeoJson layer for tectonic boundaries
folium.GeoJson(
    tectonic_plates,
    tooltip=folium.GeoJsonTooltip(fields=['Name'], aliases=['Boundary Name:']),
    color='black'
).add_to(volcano_heatmap)

# Create heatmap of volcanos
HeatMap(data=volcanos[['Latitude','Longitude']], radius=20).add_to(volcano_heatmap)

volcano_heatmap